### ISSUE TITLE
生成されるリンクがhttpになる。

### ISSUE THREAD

**Issue by vikke** [minamo173/hexo-tag-link-preview#6]
```
{% linkPreview https://www.amazon.com/ _blank nofollow %}
```
という書式で埋め込んだところ、httpsではなく、**http** のリンクが生成されています。
```
Mixed Content: The page at 'https://blog.vikke.name/' was loaded over HTTPS, but requested an insecure image 'http://g-ec2.images-amazon.com/images/G/01/social/api-share/amazon_logo_500500._V323939215_.png'. This content should also be served over HTTPS.
```
というワーニングがブラウザコンソールに出てて気がつきました。
https://developers.google.com/web/fundamentals/security/prevent-mixed-content/fixing-mixed-content?hl=ja というガイドラインが出ているようです。
対応していただけるとありがたいです。

**Comment by vikke** [comment]
元となるページのog:imageがhttpでした。
すいませんでした。

**Comment by minamo173** [comment]
@vikke 
Issue有難うございます。
なるほど、そういうことでしたか、承知しました。
